### ISSUE TITLE
Missing file

### ISSUE THREAD

**Issue by KaiserBloo** [Sixmax/Discord-Crash-MP4-Generator#2]
It requires 'C:\crashingtest\10k.png' but it is not included. Just wanted to make sure since i tried replacing it with a random image of my own, but it does not crash discord, so maybe the image needs to be exact.

**Comment by Sixmax** [comment]
Ill add the Image to the Resources soon. Also, this does indeed crash Discord. But it only works on people with Hardware Acceleration enabled. Im currently trying to figure out a better way to do it.
